#
#       @(#)tests.init	1.26 2003/12/30 Connectathon testsuite
#
MNTOPTIONS="rw,hard,intr"
# Dummy MNTPOINT definition; should get overriden by server script.
MNTPOINT="/mnt/nfs"

SERVER=""
SERVPATH="/server"
TEST="-a"
TESTARG="-t"

# set MOUNTCMD and UMOUNTCMD
# Use this mount command if using:
#	BSD
#	SunOS 4.X
#	Tru64 UNIX
#	HPUX
#	Linux
#	AIX
#	Mac OS X
# At least some BSD systems don't recognize "hard" (since that's the
# default), so you might also want to use this definition of MNTOPTIONS.
MNTOPTIONS="rw,intr"
MOUNTCMD='./domount -o $MNTOPTIONS $SERVER\:$SERVPATH $MNTPOINT'
UMOUNTCMD='./domount -u $MNTPOINT'

# set DASHN and BLC
# Use the next two lines if using:
#	BSD
#	SunOS 4.X
#	Linux
#	Tru64 UNIX
#	Mac OS X
DASHN=-n
BLC=

# set PATH
# Use this path for:
#	Tru64 UNIX
#	SVR4
#	Linux
PATH=/bin:/usr/bin:/usr/ucb:/usr/ccs/bin:/sbin:/usr/sbin:.

# -----------------------------------------------
# Defines for various variables used in scripts and makefiles.
#
# Do not remove the following three lines.  They may be overridden by
# other configuration parameters lower in this file, but these three
# variables must be defined.
CC=cc
CFLAGS=
LIBS=
LOCKTESTS=tlock
MOUNT=/bin/mount
UMOUNT=/bin/umount
LOCKTESTS=`echo tlocklfs tlock64`

# Use with Linux if your distro doesn't provide a "cc".
CC=gcc

# Use with Linux 2.2 / GNU libc 2.0
#CFLAGS=`echo -DLINUX -DGLIBC=20 -DMMAP -DSTDARG -fwritable-strings`
#LIBS=`echo -lnsl`

# Use with Linux 2.4 / GNU libc 2.2
#CFLAGS=`echo -DLINUX -DGLIBC=22 -DMMAP -DSTDARG -fwritable-strings`
#LIBS=`echo -lnsl`

# Use with Linux 2.6 / gcc 4.0
CFLAGS=`echo -DLINUX -DHAVE_SOCKLEN_T -DGLIBC=22 -DMMAP -DSTDARG`
LIBS=`echo -lnsl`

# Use with Linux glibc > 2.26
CFLAGS=`echo -DLINUX -DHAVE_SOCKLEN_T -DGLIBC=22 -DMMAP -DSTDARG`
CFLAGS+=`pkg-config --cflags libtirpc`
LIBS=`pkg-config --libs libtirpc`
